### ISSUE TITLE
HBMenu key combo default value not recognized in CFW Settings

### ISSUE THREAD

**Issue by snifer1981** [AtlasNX/Kosmos-Toolbox#1]
Comes from https://github.com/noahc3/SDSetup/issues/31

I'm using Kosmos v11.0.
In CFW Settings, the HBMenu key combo default value is not recognized (there's a question mark). If I save settings (not changing that question mark to another value), there's no way to access HBMenu anymore.

Also, B button is shown as "back", but it doesn't work. I'm not sure how to exit CFW Settings without saving. + button does nothing either.

**Comment by AetherCollective** [comment]
For now, you can reset the key combo back to the default value by setting the following value
`SDROOT:\\atmosphere\loader.ini` 
`override_key=!R`

**Comment by AnnsAnns** [comment]
Was fixed recently, I forgot to close this issue
