### ISSUE TITLE
More than 6 background services overflow; button does not react to touch input

### ISSUE THREAD

**Issue by octopuserectus** [AtlasNX/Kosmos-Toolbox#11]
As per commit 952cc03:
1. When more than 6 sysmodules are present—7th goes out of bounds—stays partially visible. It's not possible to select it via controllers, however, it can be toggled by touch. 
2. When a service requires reboot, “Okay” button that comes with the pop-up can only be pressed via controller, it does not react to touch, trying to touch the button results in toggling other entries in third bottom row.
Also, I would like to add that there is no way to go back from submenus when using touch. Not being able to navigate the whole app kinda defeats the purpose of implementing touch at all.

**Comment by friedkeenan** [comment]
This can be closed

**Comment by noahc3** [comment]
Fixed in v2.1.0 and included in Kosmos v13.2.1.
