### ISSUE TITLE
reboot to hekate broken in nyx

### ISSUE THREAD

**Issue by d3st1nyh4x** [AtlasNX/Kosmos-Toolbox#12]
reboot to hekate is broken in hekate 5.0.0, clicking reboot now will cause the switch to say the software was closed because an error occurred and actually kick you out of the title/applet

ams 9.2
hos 8.1.0
hekate 5.0.0

**Comment by friedkeenan** [comment]
Works fine for me

**Comment by d3st1nyh4x** [comment]
maybe im dumb, someone else test i coudlnt get it to work at all

**Comment by noahc3** [comment]
works for me, i tested before i pushed the release...

**Comment by noahc3** [comment]
🤔 ![](https://i.imgur.com/ibB1NP2.png)
