### ISSUE TITLE
Application not accepting joycon input

### ISSUE THREAD

**Issue by joshuajaharwood** [AtlasNX/Kosmos-Toolbox#16]
Application doesn't accept any joycon input on HOS 9.0.0.

**Comment by fennectech** [comment]
this can be closed.  HOS changed in 9.0.0. Its already fixed in libnx. latesst release may not have it but im pretty sure its fine in kosmos

**Comment by fennectech** [comment]
Simply recompiling any application affected with latest libnx will fix it

**Comment by cathery** [comment]
This should have been fixed in release 3.0.0
