### ISSUE TITLE
Can't access hb menu after closing Kosmos Toolbox

### ISSUE THREAD

**Issue by lagunyve** [AtlasNX/Kosmos-Toolbox#17]
Hello,

When I open Kosmos Toolbox to enable/disable ftpd and close it by hitting home menu, I cannot use R + Album to open hb menu, it opens the album.

It happens each time I want to enable/disable something in Kosmos Toolbox then close the menu.

Atmosphere v0.9.4 (Kosmos v14.2) 
Homebrew menu v3.1.1
Using Hekate v5.0.2

**Comment by hax4dazy** [comment]
Perhaps try to include some info about what you are using. Something like what firmware are you on? Are you using the latest kosmos? And also close the [original issue](https://github.com/AtlasNX/Kosmos/issues/254) please
