### ISSUE TITLE
Feature request: Ability to change the settings whether USB 3.0 is enabled or not.

### ISSUE THREAD

**Issue by DarthSerial** [AtlasNX/Kosmos-Toolbox#2]
In the ReSwitched-Discord Server sciresM have started a poll with the question wether USB 3.0 is activated by default or not. The background of this question are many reports of connection issues of the right Joycon if usb 3.0 is activated.

Can you implement this option in the Kosmos-Toolbox, so we are able to comfortable toggle usb 3.0 on or off?

**Comment by AnnsAnns** [comment]
Planned 👍
