### ISSUE TITLE
Kosmos Toolbox not showing Sysmodules on Atmosphère 0.10+

### ISSUE THREAD

**Issue by impeeza** [AtlasNX/Kosmos-Toolbox#20]
Since Atmosphère 0.10 the SDCARD:/Atmosphere/titles folder was renamed content, so the Kosmos Toolbox doesn't recognize any sysmodule to activate

**Comment by Tenacius-collab** [comment]
I'm a newbie, but I solved it by changing the title of the folder / atmosphere / titles / to / atmosphere / contents / in gui_sysmodule.cpp

And recompile it with devkitPro.

**Comment by impeeza** [comment]
He he he, I am more newbie,  I don't know how to compile (OK, I do know how, but haven't the compilers nor the requirements).  I did think will be something as easy as change a burn path in  source, but believe will be more complex because will be needed to test the Atmosphère version and use the adequate path.  Just I really have not the needed knowledge.  Regards

**Comment by Tenacius-collab** [comment]
> 
> 
> He he he, I am more newbie, I don't know how to compile (OK, I do know how, but haven't the compilers nor the requirements). I did think will be something as easy as change a burn path in source, but believe will be more complex because will be needed to test the Atmosphère version and use the adequate path. Just I really have not the needed knowledge. Regards

Here it is compiled with the changes in gui_sysmodule.cpp
(In the .zip is the KosmosToolbox.nro)

[KosmosToolbox.zip](https://github.com/AtlasNX/Kosmos-Toolbox/files/3956078/KosmosToolbox.zip)

**Comment by impeeza** [comment]
Thank you so much,  Regards From Colombia.

**Comment by cathery** [comment]
This was fixed in release 3.0.0
