### ISSUE TITLE
Reboot to Hekate sending to older version

### ISSUE THREAD

**Issue by KrisEnigma** [AtlasNX/Kosmos-Toolbox#21]
Hi, I don't even know how this is possible, but even if I have Hekate 5.1.0, the "Reboot to Hekate" action inside the Toolbox sends me to an older version, making it impossible to boot from it without a complete reset using the jig to load the proper version.

**Comment by Masamune3210** [comment]
You have an old version of hekate somewhere on your sd card, I believe it's payload.bin

**Comment by shchmue** [comment]
Injecting Hekate 5.1.1 should update the reboot payload automatically. Give it a try

**Comment by KrisEnigma** [comment]
I just updated to Hekate 5.1.1, and it works fine now. Thanks!
