### ISSUE TITLE
Feature request: change applet or App (titleid) to start/run hbmenu

### ISSUE THREAD

**Issue by DarthSerial** [AtlasNX/Kosmos-Toolbox#3]
It would be nice to implement the option to choose witch applet or app (TitleID) will start the hbmenu? 

In my case i use an app because i want full RAM access but after updating kosmos my settings are gone and i have to redo the steps to configure it.

you can find more information here:
https://gbatemp.net/threads/use-atmosphere-to-access-full-ram-with-homebrews-without-nsp.521240/

**Comment by AnnsAnns** [comment]
Thats kinda hard to implement - For your updating problem you could just use the ignorefile feature (Look at https://github.com/atlasnx/kosmos-updater)

**Comment by AnnsAnns** [comment]
Actually, Ill let this stay open as a suggestion

**Comment by DarthSerial** [comment]
With the currend Atmosphere release you have not to set a specific titleid anymore but have to simply add the word „app“. For example: title_id=app
With this Option enabled you can open hbmenu through any installed game (via mitm)

I think that this is a way more simplier task to add this setting into the toolbox. A simple checkbox should suffice to add this setting.

**Comment by AnnsAnns** [comment]
Outdated due to modern changes to atmos not requiring this anymore
