### ISSUE TITLE
Allow booting to UMS from kosmos toolbox

### ISSUE THREAD

**Issue by fennectech** [AtlasNX/Kosmos-Toolbox#30]
Relavant commit to new hekate
https://github.com/CTCaer/hekate/commit/abcb1dec4644e6fa77ab9b70e7e201e336d2d9f1

**Comment by AnnsAnns** [comment]
Is implemented

**Comment by fennectech** [comment]
Man.  I haven’t thought about the loams days in forever.   Good times. Sent from my iPhoneOn 20. Oct 2023, at 17:41, AnnsAnn ***@***.***> wrote:﻿
Is implemented
