### ISSUE TITLE
Feature request Bootlogo manager

### ISSUE THREAD

**Issue by fennectech** [AtlasNX/Kosmos-Toolbox#31]
Id like an option that sets the bootlogo for hekate   Just lets the user display a series of images in a folder and copy the one the user selects to /bootloader/bootlogo.bmp

**Comment by hax4dazy** [comment]
I second this

**Comment by nicholemattera** [comment]
Was talking about Hekate Icon management earlier, so I think this fits in pretty nicely.

**Comment by fennectech** [comment]
that was quick!

**Comment by fennectech** [comment]
I have a folder /bootloader/bootlogo that stores my boot logos    it makes sense to keep them there with hekate icons  Perhaps should move them to /bootloader/res/bootlogo

**Comment by AnnsAnns** [comment]
If somebody wants to implement this, feel free to send us a PR, we'll close it for now though
