### ISSUE TITLE
ums tool help?

### ISSUE THREAD

**Issue by valelisa** [AtlasNX/Kosmos-Toolbox#35]
i'm trying to modify another switch but it asks me ums tools i'm looking for it everywhere but i don't know at home it refers help me

**Comment by Masamune3210** [comment]
every reference i can find to ums tools points to it being memloader so maybe that? what is it that you are trying to do?

**Comment by WerWolv** [comment]
I don't know why this is an issue on this repo but they are most likely talking about the USB Mass Storage feature found in Hekate.
