### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by yyoossk** [AtlasNX/Kosmos-Toolbox#36]
# make
make[1]: Entering directory '/home/hiroki2/Hekate-Toolbox/SimpleIniParser'
which: no ccache in (/opt/devkitpro/portlibs/switch/bin:/opt/devkitpro/tools/bin:/opt/devkitpro/devkitA64/bin:/usr/local/bin:/usr/bin:/bin:/c/devkitPro/tools/bin:/opt/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
which: no ccache in (/opt/devkitpro/portlibs/switch/bin:/opt/devkitpro/tools/bin:/opt/devkitpro/devkitA64/bin:/opt/devkitpro/portlibs/switch/bin:/opt/devkitpro/tools/bin:/opt/devkitpro/devkitA64/bin:/usr/local/bin:/usr/bin:/bin:/c/devkitPro/tools/bin:/opt/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
make[2]: '/home/hiroki2/Hekate-Toolbox/SimpleIniParser/lib/libSimpleIniParser.a' is up to date.
which: no ccache in (/opt/devkitpro/portlibs/switch/bin:/opt/devkitpro/tools/bin:/opt/devkitpro/devkitA64/bin:/opt/devkitpro/portlibs/switch/bin:/opt/devkitpro/tools/bin:/opt/devkitpro/devkitA64/bin:/usr/local/bin:/usr/bin:/bin:/c/devkitPro/tools/bin:/opt/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
make[2]: '/home/hiroki2/Hekate-Toolbox/SimpleIniParser/lib/libSimpleIniParserd.a' is up to date.
make[1]: Leaving directory '/home/hiroki2/Hekate-Toolbox/SimpleIniParser'
main.cpp
In file included from C:/Users/hiroki2/Hekate-Toolbox/include/gui/gui.hpp:7,
                 from C:/Users/hiroki2/Hekate-Toolbox/source/main.cpp:8:
C:/Users/hiroki2/Hekate-Toolbox/include/gui/list_selector.hpp:21:16: error: 'touchPosition' has not been declared
   21 |   void onTouch(touchPosition &touch);
      |                ^~~~~~~~~~~~~
In file included from C:/Users/hiroki2/Hekate-Toolbox/include/gui/gui.hpp:8,
                 from C:/Users/hiroki2/Hekate-Toolbox/source/main.cpp:8:
C:/Users/hiroki2/Hekate-Toolbox/include/gui/message_box.hpp:31:16: error: 'touchPosition' has not been declared
   31 |   void onTouch(touchPosition &touch);
      |                ^~~~~~~~~~~~~
C:/Users/hiroki2/Hekate-Toolbox/include/gui/message_box.hpp:32:18: error: 'touchPosition' has not been declared
   32 |   void onGesture(touchPosition startPosition, touchPosition endPosition, bool finish);
      |                  ^~~~~~~~~~~~~
C:/Users/hiroki2/Hekate-Toolbox/include/gui/message_box.hpp:32:47: error: 'touchPosition' has not been declared
   32 |   void onGesture(touchPosition startPosition, touchPosition endPosition, bool finish);
      |                                               ^~~~~~~~~~~~~
In file included from C:/Users/hiroki2/Hekate-Toolbox/source/main.cpp:8:
C:/Users/hiroki2/Hekate-Toolbox/include/gui/gui.hpp:59:24: error: 'touchPosition' has not been declared
   59 |   virtual void onTouch(touchPosition &touch) = 0;
      |                        ^~~~~~~~~~~~~
C:/Users/hiroki2/Hekate-Toolbox/include/gui/gui.hpp:60:26: error: 'touchPosition' has not been declared
   60 |   virtual void onGesture(touchPosition &startPosition, touchPosition &endPosition) = 0;
      |                          ^~~~~~~~~~~~~
C:/Users/hiroki2/Hekate-Toolbox/include/gui/gui.hpp:60:56: error: 'touchPosition' has not been declared
   60 |   virtual void onGesture(touchPosition &startPosition, touchPosition &endPosition) = 0;
      |                                                        ^~~~~~~~~~~~~
In file included from C:/Users/hiroki2/Hekate-Toolbox/include/gui/gui_main.hpp:9,
                 from C:/Users/hiroki2/Hekate-Toolbox/source/main.cpp:9:
C:/Users/hiroki2/Hekate-Toolbox/include/utils/override_key.hpp:23:3: error: 'HidControllerKeys' does not name a type
   23 |   HidControllerKeys key;
      |   ^~~~~~~~~~~~~~~~~
C:/Users/hiroki2/Hekate-Toolbox/include/utils/override_key.hpp:32:22: error: expected ';' at end of member declaration
   32 |   static const char* KeyToUnicode(HidControllerKeys key);
      |                      ^~~~~~~~~~~~
      |                                  ;
C:/Users/hiroki2/Hekate-Toolbox/include/utils/override_key.hpp:32:52: error: expected ')' before 'key'
   32 |   static const char* KeyToUnicode(HidControllerKeys key);
      |                                  ~                 ^~~~
      |                                                    )
In file included from C:/Users/hiroki2/Hekate-Toolbox/source/main.cpp:9:
C:/Users/hiroki2/Hekate-Toolbox/include/gui/gui_main.hpp:19:16: error: 'touchPosition' has not been declared
   19 |   void onTouch(touchPosition &touch);
      |                ^~~~~~~~~~~~~
C:/Users/hiroki2/Hekate-Toolbox/include/gui/gui_main.hpp:20:18: error: 'touchPosition' has not been declared
   20 |   void onGesture(touchPosition &startPosition, touchPosition &endPosition);
      |                  ^~~~~~~~~~~~~
C:/Users/hiroki2/Hekate-Toolbox/include/gui/gui_main.hpp:20:48: error: 'touchPosition' has not been declared
   20 |   void onGesture(touchPosition &startPosition, touchPosition &endPosition);
      |                                                ^~~~~~~~~~~~~
In file included from C:/Users/hiroki2/Hekate-Toolbox/source/main.cpp:10:
C:/Users/hiroki2/Hekate-Toolbox/include/gui/gui_sysmodule.hpp:24:16: error: 'touchPosition' has not been declared
   24 |   void onTouch(touchPosition &touch);
      |                ^~~~~~~~~~~~~
C:/Users/hiroki2/Hekate-Toolbox/include/gui/gui_sysmodule.hpp:25:18: error: 'touchPosition' has not been declared
   25 |   void onGesture(touchPosition &startPosition, touchPosition &endPosition);
      |                  ^~~~~~~~~~~~~
C:/Users/hiroki2/Hekate-Toolbox/include/gui/gui_sysmodule.hpp:25:48: error: 'touchPosition' has not been declared
   25 |   void onGesture(touchPosition &startPosition, touchPosition &endPosition);
      |                                                ^~~~~~~~~~~~~
In file included from C:/Users/hiroki2/Hekate-Toolbox/source/main.cpp:11:
C:/Users/hiroki2/Hekate-Toolbox/include/gui/gui_hekate.hpp:20:16: error: 'touchPosition' has not been declared
   20 |   void onTouch(touchPosition &touch);
      |                ^~~~~~~~~~~~~
C:/Users/hiroki2/Hekate-Toolbox/include/gui/gui_hekate.hpp:21:18: error: 'touchPosition' has not been declared
   21 |   void onGesture(touchPosition &startPosition, touchPosition &endPosition);
      |                  ^~~~~~~~~~~~~
C:/Users/hiroki2/Hekate-Toolbox/include/gui/gui_hekate.hpp:21:48: error: 'touchPosition' has not been declared
   21 |   void onGesture(touchPosition &startPosition, touchPosition &endPosition);
      |                                                ^~~~~~~~~~~~~
In file included from C:/Users/hiroki2/Hekate-Toolbox/source/main.cpp:12:
C:/Users/hiroki2/Hekate-Toolbox/include/gui/gui_hid_mitm.hpp:20:16: error: 'touchPosition' has not been declared
   20 |   void onTouch(touchPosition &touch);
      |                ^~~~~~~~~~~~~
C:/Users/hiroki2/Hekate-Toolbox/include/gui/gui_hid_mitm.hpp:21:18: error: 'touchPosition' has not been declared
   21 |   void onGesture(touchPosition &startPosition, touchPosition &endPosition);
      |                  ^~~~~~~~~~~~~
C:/Users/hiroki2/Hekate-Toolbox/include/gui/gui_hid_mitm.hpp:21:48: error: 'touchPosition' has not been declared
   21 |   void onGesture(touchPosition &startPosition, touchPosition &endPosition);
      |                                                ^~~~~~~~~~~~~
In file included from C:/Users/hiroki2/Hekate-Toolbox/source/main.cpp:13:
C:/Users/hiroki2/Hekate-Toolbox/include/gui/gui_overrides_menu.hpp:20:16: error: 'touchPosition' has not been declared
   20 |   void onTouch(touchPosition &touch);
      |                ^~~~~~~~~~~~~
C:/Users/hiroki2/Hekate-Toolbox/include/gui/gui_overrides_menu.hpp:21:18: error: 'touchPosition' has not been declared
   21 |   void onGesture(touchPosition &startPosition, touchPosition &endPosition);
      |                  ^~~~~~~~~~~~~
C:/Users/hiroki2/Hekate-Toolbox/include/gui/gui_overrides_menu.hpp:21:48: error: 'touchPosition' has not been declared
   21 |   void onGesture(touchPosition &startPosition, touchPosition &endPosition);
      |                                                ^~~~~~~~~~~~~
In file included from C:/Users/hiroki2/Hekate-Toolbox/source/main.cpp:14:
C:/Users/hiroki2/Hekate-Toolbox/include/gui/gui_override_key.hpp:15:16: error: 'touchPosition' has not been declared
   15 |   void onTouch(touchPosition &touch);
      |                ^~~~~~~~~~~~~
C:/Users/hiroki2/Hekate-Toolbox/include/gui/gui_override_key.hpp:16:18: error: 'touchPosition' has not been declared
   16 |   void onGesture(touchPosition &startPosition, touchPosition &endPosition);
      |                  ^~~~~~~~~~~~~
C:/Users/hiroki2/Hekate-Toolbox/include/gui/gui_override_key.hpp:16:48: error: 'touchPosition' has not been declared
   16 |   void onGesture(touchPosition &startPosition, touchPosition &endPosition);
      |                                                ^~~~~~~~~~~~~
In file included from C:/Users/hiroki2/Hekate-Toolbox/source/main.cpp:15:
C:/Users/hiroki2/Hekate-Toolbox/include/gui/gui_title_list.hpp:14:16: error: 'touchPosition' has not been declared
   14 |   void onTouch(touchPosition &touch);
      |                ^~~~~~~~~~~~~
C:/Users/hiroki2/Hekate-Toolbox/include/gui/gui_title_list.hpp:15:18: error: 'touchPosition' has not been declared
   15 |   void onGesture(touchPosition &startPosition, touchPosition &endPosition);
      |                  ^~~~~~~~~~~~~
C:/Users/hiroki2/Hekate-Toolbox/include/gui/gui_title_list.hpp:15:48: error: 'touchPosition' has not been declared
   15 |   void onGesture(touchPosition &startPosition, touchPosition &endPosition);
      |                                                ^~~~~~~~~~~~~
In file included from C:/Users/hiroki2/Hekate-Toolbox/source/main.cpp:16:
C:/Users/hiroki2/Hekate-Toolbox/include/gui/button.hpp:27:16: error: 'touchPosition' has not been declared
   27 |   void onTouch(touchPosition &touch);
      |                ^~~~~~~~~~~~~
C:/Users/hiroki2/Hekate-Toolbox/source/main.cpp: In function 'int main(int, char**)':
C:/Users/hiroki2/Hekate-Toolbox/source/main.cpp:54:5: error: 'touchPosition' was not declared in this scope
   54 |     touchPosition touch;
      |     ^~~~~~~~~~~~~
C:/Users/hiroki2/Hekate-Toolbox/source/main.cpp:82:19: error: 'hidTouchCount' was not declared in this scope
   82 |     touchCntOld = hidTouchCount();
      |                   ^~~~~~~~~~~~~
C:/Users/hiroki2/Hekate-Toolbox/source/main.cpp:85:7: error: 'hidScanInput' was not declared in this scope
   85 |       hidScanInput();
      |       ^~~~~~~~~~~~
C:/Users/hiroki2/Hekate-Toolbox/source/main.cpp:89:42: error: 'HidControllerID' does not name a type; did you mean 'FanController'?
   89 |         kdown |= hidKeysDown(static_cast<HidControllerID>(controller));
      |                                          ^~~~~~~~~~~~~~~
      |                                          FanController
C:/Users/hiroki2/Hekate-Toolbox/source/main.cpp:89:18: error: 'hidKeysDown' was not declared in this scope
   89 |         kdown |= hidKeysDown(static_cast<HidControllerID>(controller));
      |                  ^~~~~~~~~~~
C:/Users/hiroki2/Hekate-Toolbox/source/main.cpp:90:42: error: 'HidControllerID' does not name a type; did you mean 'FanController'?
   90 |         kheld |= hidKeysHeld(static_cast<HidControllerID>(controller));
      |                                          ^~~~~~~~~~~~~~~
      |                                          FanController
C:/Users/hiroki2/Hekate-Toolbox/source/main.cpp:90:18: error: 'hidKeysHeld' was not declared in this scope
   90 |         kheld |= hidKeysHeld(static_cast<HidControllerID>(controller));
      |                  ^~~~~~~~~~~
C:/Users/hiroki2/Hekate-Toolbox/source/main.cpp:93:21: error: 'KEY_UP' was not declared in this scope
   93 |       if ((kheld & (KEY_UP | KEY_DOWN | KEY_LEFT | KEY_RIGHT)) && kheld == lastkheld)
      |                     ^~~~~~
C:/Users/hiroki2/Hekate-Toolbox/source/main.cpp:93:30: error: 'KEY_DOWN' was not declared in this scope
   93 |       if ((kheld & (KEY_UP | KEY_DOWN | KEY_LEFT | KEY_RIGHT)) && kheld == lastkheld)
      |                              ^~~~~~~~
C:/Users/hiroki2/Hekate-Toolbox/source/main.cpp:93:41: error: 'KEY_LEFT' was not declared in this scope
   93 |       if ((kheld & (KEY_UP | KEY_DOWN | KEY_LEFT | KEY_RIGHT)) && kheld == lastkheld)
      |                                         ^~~~~~~~
C:/Users/hiroki2/Hekate-Toolbox/source/main.cpp:93:52: error: 'KEY_RIGHT' was not declared in this scope
   93 |       if ((kheld & (KEY_UP | KEY_DOWN | KEY_LEFT | KEY_RIGHT)) && kheld == lastkheld)
      |                                                    ^~~~~~~~~
C:/Users/hiroki2/Hekate-Toolbox/source/main.cpp:150:29: error: 'KEY_PLUS' was not declared in this scope
  150 |           else if ((kdown & KEY_PLUS) && !Gui::g_exitBlocked)
      |                             ^~~~~~~~
C:/Users/hiroki2/Hekate-Toolbox/source/main.cpp:168:25: error: 'touch' was not declared in this scope; did you mean 'touchCnt'?
  168 |           hidTouchRead(&touch, 0);
      |                         ^~~~~
      |                         touchCnt
C:/Users/hiroki2/Hekate-Toolbox/source/main.cpp:168:11: error: 'hidTouchRead' was not declared in this scope
  168 |           hidTouchRead(&touch, 0);
      |           ^~~~~~~~~~~~
make[1]: *** [/opt/devkitpro/devkitA64/base_rules:14: main.o] Error 1
make: *** [Makefile:163: build] Error 2

**Comment by cathery** [comment]
The `dev` branch should be more up to date.
