### ISSUE TITLE
[bug] Sys-botbase not listed in sysmodules list

### ISSUE THREAD

**Issue by DraconicNEO** [AtlasNX/Kosmos-Toolbox#38]
I noticed while trying to use this tool that [sys-botbase](https://github.com/olliz0r/sys-botbase) isn't listed in the list of sysmodules which it should be since it's an active sysmodule.

**Comment by WerWolv** [comment]
Sysmodule devs need to provide a `toolbox.json` file in the relevant sysmodule folder for the Toolbox to pick it up. You can make one yourself by following the format other sysmodules use or pester sys-botbase's dev to do it

**Comment by DraconicNEO** [comment]
> Sysmodule devs need to provide a `toolbox.json` file in the relevant sysmodule folder for the Toolbox to pick it up. You can make one yourself by following the format other sysmodules use or pester sys-botbase's dev to do it

Oh I see, well thank you for that information. That seems easy enough to do.
