### ISSUE TITLE
[Feature Request] Add News and NSO app redirection options 

### ISSUE THREAD

**Issue by DraconicNEO** [AtlasNX/Kosmos-Toolbox#39]
I think it would be a good idea to add news and NSO app options in the redirect settings so people are able to use those as redirects in this tool.

**Comment by AnnsAnns** [comment]
If I remember correctly there was some issue with that, maybe you know more @WerWolv?

**Comment by DraconicNEO** [comment]
> If I remember correctly there was some issue with that, maybe you know more @WerWolv?

I'd definitely like to know more about that as well, I guess maybe NSO could have issues since it's a web browser, but I don't see why news would be a problem.

**Comment by WerWolv** [comment]
The issue is that "News" isn't a separate applet, it's part of qlaunch so you can't replace it. Also the NSO app is just the browser applet, you also can't replace it without replacing every other instance of the browser too.

**Comment by DraconicNEO** [comment]
> The issue is that "News" isn't a separate applet, it's part of qlaunch so you can't replace it. Also the NSO app is just the browser applet, you also can't replace it without replacing every other instance of the browser too.

Oh I see, that makes sense. I thought though that the NSO app was different than the stock browser since it has that built in overlay that appears even when Nintendo servers are blocked or am I missing something?

**Comment by Masamune3210** [comment]
Some elements are permenently cached, its still the web browser though
