### ISSUE TITLE
please update for 16.0.1

### ISSUE THREAD

**Issue by f3bandit** [AtlasNX/Kosmos-Toolbox#40]
please update for 16.0.1

**Comment by AnnsAnns** [comment]
A new release has been made

**Comment by pixeltester** [comment]
It was already working completely fine on 16.0.1, I've been using it for weeks?

**Comment by AnnsAnns** [comment]
Might be, can't comment on that.

Either way, given that the last release is over 6 months old updating it's libraries made sense either way.

**Comment by f3bandit** [comment]
awesome, thank you so much!
