### ISSUE TITLE
support for OLED switch ?

### ISSUE THREAD

**Issue by ZweiBR** [AtlasNX/Kosmos-Toolbox#41]
v4.0.3 - Firmware v16 .0.3

I would like to know if there is support for OLED in the reboot to hetake part?

**Comment by AnnsAnns** [comment]
We have some restrictions in place for Mariko Switches and other non-supported devices. Normally, _and this isn't guaranteed_, Hekate Toolbox should show a warning screen when running it on unsupported devices and disable the reboot support, however, all other parts should work fine.
