### ISSUE TITLE
firmware 17.0.0

### ISSUE THREAD

**Issue by ZweiBR** [AtlasNX/Kosmos-Toolbox#43]
support for firmware 17.0.0?

**Comment by hax4dazy** [comment]
I'm not sure what you mean? The latest Hekate toolbox already supports firmware version 17.0.0

**Comment by ZweiBR** [comment]
> I'm not sure what you mean? The latest Hekate toolbox already supports firmware version 17.0.0

good to know
I tested it here and it works fine on 17.0.0
thanks

**Comment by AnnsAnns** [comment]
Closing, ty @hax4dazy 👍
