### ISSUE TITLE
Freature request: abillity to use reboot to payload and change heakte boot options to autoboot to cfw after update

### ISSUE THREAD

**Issue by DarthSerial** [AtlasNX/Kosmos-Toolbox#5]
## Feature Request

1. Ability to set hekate boot options after update, so f.e. after a reboot it would autoboot into CFW instead to boot in to hekate boot menu.
2. It would also be nice if you can detect that the reboot_payload.bin is in place and after an update we could use the option to reboot to payload.

**Comment by nicholemattera** [comment]
Well I think the reboot to payload is a good idea. Seeing as I already have reboot in there. I'll just add another issue in Kosmos Updater.
