### ISSUE TITLE
Crash when launched on Switch Firmware 7.0.1, Kosmos 11.10.1

### ISSUE THREAD

**Issue by Primeey** [AtlasNX/Kosmos-Toolbox#6]
It crashes as soon as it tries to launch. Here's the atmosphere error screen

![img_20190224_151135](https://user-images.githubusercontent.com/8511642/53301099-b2320700-3846-11e9-8c51-a7a96945a050.jpg) (Sorry, I'm not sure if you can screenshot the error screen)

**Comment by AnnsAnns** [comment]
We have identified the issue (a change in atmosphere's config) and will fix it in a upcoming update.
