### ISSUE TITLE
Odd behavior of album combo key with Kosmos 11.11.1 and 0.8.6 atmos

### ISSUE THREAD

**Issue by ghost** [AtlasNX/Kosmos-Toolbox#7]
Hello,

Not sure if a bug or not, sorry but I don't remember how it used to work on older versions.

Basically if I do this:
1. Open album -> opens album, as default behavior now is to use a key (R default).
2. Open R + Album -> opens HBL.
3. Open kosmos toolbox. Set "open album by default" to off, then on back again (don't think this step is necessary, shouldn't force the app to make any changes on sdcard). But on album combo key it shows "?". Save by pressing home button.
4. Open album -> Opens album.
5. Open album -> Opens album.

As you can see combo key was cleared out (guess that's why it shows "?" in the toolbox).
If i look at atmos/loader.ini
```
[hbl_config]
title_id=010000000000100D
override_any_app=true
path=atmosphere/hbl.nsp
override_key=
```

override_key was cleared.
Now, the question is, should the toolbox be updated to be able to read override_key value (default "R") and set it on the UI? Because currently it's not doing it, I guess because override_key is a new option in the ini.

**Comment by WerWolv** [comment]
Get the latest version of the toolbox. This was fixed some time ago

**Comment by ghost** [comment]
I'm using latest version via sdsetup, binary compared vs kosmos/modules, same version.

So I assume let's say the "open album by default" set to off, then on, press home = clears **override_key** (was able to reproduce it three times now) is that kind of unnecessary QA test case you wouldn't want to fix.

But what about the ? symbol on the left, shouldn't it read from override_key and set it to "R" with default loader.ini bundled in 0.8.6? This is how it loads every time
![2019032707145400-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/21700114/55075173-4965c680-5060-11e9-9d59-24e7cad89f88.jpg)
